// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nodemgmt.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
	drpc "storj.io/drpc"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Pagination struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{0}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetMgmtStatsRequest struct {
	Page                 *Pagination `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMgmtStatsRequest) Reset()         { *m = GetMgmtStatsRequest{} }
func (m *GetMgmtStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStatsRequest) ProtoMessage()    {}
func (*GetMgmtStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{1}
}
func (m *GetMgmtStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStatsRequest.Unmarshal(m, b)
}
func (m *GetMgmtStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetMgmtStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStatsRequest.Merge(m, src)
}
func (m *GetMgmtStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStatsRequest.Size(m)
}
func (m *GetMgmtStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStatsRequest proto.InternalMessageInfo

func (m *GetMgmtStatsRequest) GetPage() *Pagination {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetMgmtStatsResponse struct {
	NextPage             *Pagination                       `protobuf:"bytes,1,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	NodeStats            []*GetMgmtStatsResponse_NodeStats `protobuf:"bytes,2,rep,name=node_stats,json=nodeStats,proto3" json:"node_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetMgmtStatsResponse) Reset()         { *m = GetMgmtStatsResponse{} }
func (m *GetMgmtStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStatsResponse) ProtoMessage()    {}
func (*GetMgmtStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{2}
}
func (m *GetMgmtStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStatsResponse.Unmarshal(m, b)
}
func (m *GetMgmtStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetMgmtStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStatsResponse.Merge(m, src)
}
func (m *GetMgmtStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStatsResponse.Size(m)
}
func (m *GetMgmtStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStatsResponse proto.InternalMessageInfo

func (m *GetMgmtStatsResponse) GetNextPage() *Pagination {
	if m != nil {
		return m.NextPage
	}
	return nil
}

func (m *GetMgmtStatsResponse) GetNodeStats() []*GetMgmtStatsResponse_NodeStats {
	if m != nil {
		return m.NodeStats
	}
	return nil
}

type GetMgmtStatsResponse_Reputation struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SuccessCount         int64    `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ReputationAlpha      float64  `protobuf:"fixed64,3,opt,name=reputation_alpha,json=reputationAlpha,proto3" json:"reputation_alpha,omitempty"`
	ReputationBeta       float64  `protobuf:"fixed64,4,opt,name=reputation_beta,json=reputationBeta,proto3" json:"reputation_beta,omitempty"`
	ReputationScore      float64  `protobuf:"fixed64,5,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMgmtStatsResponse_Reputation) Reset()         { *m = GetMgmtStatsResponse_Reputation{} }
func (m *GetMgmtStatsResponse_Reputation) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStatsResponse_Reputation) ProtoMessage()    {}
func (*GetMgmtStatsResponse_Reputation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{2, 0}
}
func (m *GetMgmtStatsResponse_Reputation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStatsResponse_Reputation.Unmarshal(m, b)
}
func (m *GetMgmtStatsResponse_Reputation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStatsResponse_Reputation.Marshal(b, m, deterministic)
}
func (m *GetMgmtStatsResponse_Reputation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStatsResponse_Reputation.Merge(m, src)
}
func (m *GetMgmtStatsResponse_Reputation) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStatsResponse_Reputation.Size(m)
}
func (m *GetMgmtStatsResponse_Reputation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStatsResponse_Reputation.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStatsResponse_Reputation proto.InternalMessageInfo

func (m *GetMgmtStatsResponse_Reputation) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetMgmtStatsResponse_Reputation) GetSuccessCount() int64 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

func (m *GetMgmtStatsResponse_Reputation) GetReputationAlpha() float64 {
	if m != nil {
		return m.ReputationAlpha
	}
	return 0
}

func (m *GetMgmtStatsResponse_Reputation) GetReputationBeta() float64 {
	if m != nil {
		return m.ReputationBeta
	}
	return 0
}

func (m *GetMgmtStatsResponse_Reputation) GetReputationScore() float64 {
	if m != nil {
		return m.ReputationScore
	}
	return 0
}

type GetMgmtStatsResponse_Stats struct {
	UptimeCheck          *GetMgmtStatsResponse_Reputation `protobuf:"bytes,1,opt,name=uptime_check,json=uptimeCheck,proto3" json:"uptime_check,omitempty"`
	AuditCheck           *GetMgmtStatsResponse_Reputation `protobuf:"bytes,2,opt,name=audit_check,json=auditCheck,proto3" json:"audit_check,omitempty"`
	Disqualified         *time.Time                       `protobuf:"bytes,3,opt,name=disqualified,proto3,stdtime" json:"disqualified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetMgmtStatsResponse_Stats) Reset()         { *m = GetMgmtStatsResponse_Stats{} }
func (m *GetMgmtStatsResponse_Stats) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStatsResponse_Stats) ProtoMessage()    {}
func (*GetMgmtStatsResponse_Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{2, 1}
}
func (m *GetMgmtStatsResponse_Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStatsResponse_Stats.Unmarshal(m, b)
}
func (m *GetMgmtStatsResponse_Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStatsResponse_Stats.Marshal(b, m, deterministic)
}
func (m *GetMgmtStatsResponse_Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStatsResponse_Stats.Merge(m, src)
}
func (m *GetMgmtStatsResponse_Stats) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStatsResponse_Stats.Size(m)
}
func (m *GetMgmtStatsResponse_Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStatsResponse_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStatsResponse_Stats proto.InternalMessageInfo

func (m *GetMgmtStatsResponse_Stats) GetUptimeCheck() *GetMgmtStatsResponse_Reputation {
	if m != nil {
		return m.UptimeCheck
	}
	return nil
}

func (m *GetMgmtStatsResponse_Stats) GetAuditCheck() *GetMgmtStatsResponse_Reputation {
	if m != nil {
		return m.AuditCheck
	}
	return nil
}

func (m *GetMgmtStatsResponse_Stats) GetDisqualified() *time.Time {
	if m != nil {
		return m.Disqualified
	}
	return nil
}

type GetMgmtStatsResponse_NodeStats struct {
	NodeId               NodeID                      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	Stats                *GetMgmtStatsResponse_Stats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetMgmtStatsResponse_NodeStats) Reset()         { *m = GetMgmtStatsResponse_NodeStats{} }
func (m *GetMgmtStatsResponse_NodeStats) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStatsResponse_NodeStats) ProtoMessage()    {}
func (*GetMgmtStatsResponse_NodeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{2, 2}
}
func (m *GetMgmtStatsResponse_NodeStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStatsResponse_NodeStats.Unmarshal(m, b)
}
func (m *GetMgmtStatsResponse_NodeStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStatsResponse_NodeStats.Marshal(b, m, deterministic)
}
func (m *GetMgmtStatsResponse_NodeStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStatsResponse_NodeStats.Merge(m, src)
}
func (m *GetMgmtStatsResponse_NodeStats) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStatsResponse_NodeStats.Size(m)
}
func (m *GetMgmtStatsResponse_NodeStats) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStatsResponse_NodeStats.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStatsResponse_NodeStats proto.InternalMessageInfo

func (m *GetMgmtStatsResponse_NodeStats) GetStats() *GetMgmtStatsResponse_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type GetMgmtStorageUsageRequest struct {
	Page                 *Pagination `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	From                 time.Time   `protobuf:"bytes,2,opt,name=from,proto3,stdtime" json:"from"`
	To                   time.Time   `protobuf:"bytes,3,opt,name=to,proto3,stdtime" json:"to"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMgmtStorageUsageRequest) Reset()         { *m = GetMgmtStorageUsageRequest{} }
func (m *GetMgmtStorageUsageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStorageUsageRequest) ProtoMessage()    {}
func (*GetMgmtStorageUsageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{3}
}
func (m *GetMgmtStorageUsageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStorageUsageRequest.Unmarshal(m, b)
}
func (m *GetMgmtStorageUsageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStorageUsageRequest.Marshal(b, m, deterministic)
}
func (m *GetMgmtStorageUsageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStorageUsageRequest.Merge(m, src)
}
func (m *GetMgmtStorageUsageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStorageUsageRequest.Size(m)
}
func (m *GetMgmtStorageUsageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStorageUsageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStorageUsageRequest proto.InternalMessageInfo

func (m *GetMgmtStorageUsageRequest) GetPage() *Pagination {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetMgmtStorageUsageRequest) GetFrom() time.Time {
	if m != nil {
		return m.From
	}
	return time.Time{}
}

func (m *GetMgmtStorageUsageRequest) GetTo() time.Time {
	if m != nil {
		return m.To
	}
	return time.Time{}
}

type GetMgmtStorageUsageResponse struct {
	NextPage             *Pagination                                     `protobuf:"bytes,1,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	NodeStorageUsage     []*GetMgmtStorageUsageResponse_NodeStorageUsage `protobuf:"bytes,2,rep,name=node_storage_usage,json=nodeStorageUsage,proto3" json:"node_storage_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *GetMgmtStorageUsageResponse) Reset()         { *m = GetMgmtStorageUsageResponse{} }
func (m *GetMgmtStorageUsageResponse) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStorageUsageResponse) ProtoMessage()    {}
func (*GetMgmtStorageUsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{4}
}
func (m *GetMgmtStorageUsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStorageUsageResponse.Unmarshal(m, b)
}
func (m *GetMgmtStorageUsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStorageUsageResponse.Marshal(b, m, deterministic)
}
func (m *GetMgmtStorageUsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStorageUsageResponse.Merge(m, src)
}
func (m *GetMgmtStorageUsageResponse) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStorageUsageResponse.Size(m)
}
func (m *GetMgmtStorageUsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStorageUsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStorageUsageResponse proto.InternalMessageInfo

func (m *GetMgmtStorageUsageResponse) GetNextPage() *Pagination {
	if m != nil {
		return m.NextPage
	}
	return nil
}

func (m *GetMgmtStorageUsageResponse) GetNodeStorageUsage() []*GetMgmtStorageUsageResponse_NodeStorageUsage {
	if m != nil {
		return m.NodeStorageUsage
	}
	return nil
}

type GetMgmtStorageUsageResponse_StorageUsage struct {
	AtRestTotal          float64   `protobuf:"fixed64,1,opt,name=at_rest_total,json=atRestTotal,proto3" json:"at_rest_total,omitempty"`
	Timestamp            time.Time `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMgmtStorageUsageResponse_StorageUsage) Reset() {
	*m = GetMgmtStorageUsageResponse_StorageUsage{}
}
func (m *GetMgmtStorageUsageResponse_StorageUsage) String() string { return proto.CompactTextString(m) }
func (*GetMgmtStorageUsageResponse_StorageUsage) ProtoMessage()    {}
func (*GetMgmtStorageUsageResponse_StorageUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{4, 0}
}
func (m *GetMgmtStorageUsageResponse_StorageUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStorageUsageResponse_StorageUsage.Unmarshal(m, b)
}
func (m *GetMgmtStorageUsageResponse_StorageUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStorageUsageResponse_StorageUsage.Marshal(b, m, deterministic)
}
func (m *GetMgmtStorageUsageResponse_StorageUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStorageUsageResponse_StorageUsage.Merge(m, src)
}
func (m *GetMgmtStorageUsageResponse_StorageUsage) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStorageUsageResponse_StorageUsage.Size(m)
}
func (m *GetMgmtStorageUsageResponse_StorageUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStorageUsageResponse_StorageUsage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStorageUsageResponse_StorageUsage proto.InternalMessageInfo

func (m *GetMgmtStorageUsageResponse_StorageUsage) GetAtRestTotal() float64 {
	if m != nil {
		return m.AtRestTotal
	}
	return 0
}

func (m *GetMgmtStorageUsageResponse_StorageUsage) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

type GetMgmtStorageUsageResponse_NodeStorageUsage struct {
	NodeId               NodeID                                      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	StorageUsage         []*GetMgmtStorageUsageResponse_StorageUsage `protobuf:"bytes,2,rep,name=storage_usage,json=storageUsage,proto3" json:"storage_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) Reset() {
	*m = GetMgmtStorageUsageResponse_NodeStorageUsage{}
}
func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) String() string {
	return proto.CompactTextString(m)
}
func (*GetMgmtStorageUsageResponse_NodeStorageUsage) ProtoMessage() {}
func (*GetMgmtStorageUsageResponse_NodeStorageUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e005f111732f9e6, []int{4, 1}
}
func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMgmtStorageUsageResponse_NodeStorageUsage.Unmarshal(m, b)
}
func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMgmtStorageUsageResponse_NodeStorageUsage.Marshal(b, m, deterministic)
}
func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMgmtStorageUsageResponse_NodeStorageUsage.Merge(m, src)
}
func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) XXX_Size() int {
	return xxx_messageInfo_GetMgmtStorageUsageResponse_NodeStorageUsage.Size(m)
}
func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMgmtStorageUsageResponse_NodeStorageUsage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMgmtStorageUsageResponse_NodeStorageUsage proto.InternalMessageInfo

func (m *GetMgmtStorageUsageResponse_NodeStorageUsage) GetStorageUsage() []*GetMgmtStorageUsageResponse_StorageUsage {
	if m != nil {
		return m.StorageUsage
	}
	return nil
}

func init() {
	proto.RegisterType((*Pagination)(nil), "nodemgmt.Pagination")
	proto.RegisterType((*GetMgmtStatsRequest)(nil), "nodemgmt.GetMgmtStatsRequest")
	proto.RegisterType((*GetMgmtStatsResponse)(nil), "nodemgmt.GetMgmtStatsResponse")
	proto.RegisterType((*GetMgmtStatsResponse_Reputation)(nil), "nodemgmt.GetMgmtStatsResponse.Reputation")
	proto.RegisterType((*GetMgmtStatsResponse_Stats)(nil), "nodemgmt.GetMgmtStatsResponse.Stats")
	proto.RegisterType((*GetMgmtStatsResponse_NodeStats)(nil), "nodemgmt.GetMgmtStatsResponse.NodeStats")
	proto.RegisterType((*GetMgmtStorageUsageRequest)(nil), "nodemgmt.GetMgmtStorageUsageRequest")
	proto.RegisterType((*GetMgmtStorageUsageResponse)(nil), "nodemgmt.GetMgmtStorageUsageResponse")
	proto.RegisterType((*GetMgmtStorageUsageResponse_StorageUsage)(nil), "nodemgmt.GetMgmtStorageUsageResponse.StorageUsage")
	proto.RegisterType((*GetMgmtStorageUsageResponse_NodeStorageUsage)(nil), "nodemgmt.GetMgmtStorageUsageResponse.NodeStorageUsage")
}

func init() { proto.RegisterFile("nodemgmt.proto", fileDescriptor_7e005f111732f9e6) }

var fileDescriptor_7e005f111732f9e6 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0x3a, 0x3f, 0x24, 0x63, 0xa7, 0x54, 0x4b, 0x85, 0x22, 0x23, 0x48, 0x14, 0x8a, 0x9a,
	0x5e, 0x52, 0x11, 0x10, 0x42, 0xbd, 0x20, 0x52, 0xa4, 0x52, 0x44, 0x51, 0xe5, 0x16, 0x21, 0x71,
	0xb1, 0x36, 0xf1, 0xc6, 0xb5, 0x88, 0xbd, 0x6e, 0x76, 0x8d, 0x78, 0x0c, 0x0e, 0x3c, 0x0b, 0x37,
	0x8e, 0xa0, 0x5e, 0xb9, 0x72, 0x28, 0x0f, 0xc0, 0x4b, 0xa0, 0xdd, 0x75, 0x62, 0x37, 0x04, 0x92,
	0x70, 0xf3, 0x7c, 0x9e, 0xf9, 0x66, 0xe6, 0xf3, 0x37, 0x86, 0xf5, 0x88, 0x79, 0x34, 0xf4, 0x43,
	0xd1, 0x89, 0xc7, 0x4c, 0x30, 0x5c, 0x99, 0xc4, 0x36, 0xf8, 0xcc, 0x67, 0x1a, 0xb5, 0x1b, 0x3e,
	0x63, 0xfe, 0x88, 0xee, 0xaa, 0xa8, 0x9f, 0x0c, 0x77, 0x45, 0x10, 0x52, 0x2e, 0x48, 0x18, 0xeb,
	0x84, 0xd6, 0x1e, 0xc0, 0x31, 0xf1, 0x83, 0x88, 0x88, 0x80, 0x45, 0x78, 0x13, 0x4a, 0xa3, 0x20,
	0x0c, 0x44, 0x1d, 0x35, 0x51, 0xbb, 0xe6, 0xe8, 0x00, 0xdf, 0x84, 0x32, 0x1b, 0x0e, 0x39, 0x15,
	0x75, 0xa3, 0x89, 0xda, 0x45, 0x27, 0x8d, 0x5a, 0x4f, 0xe0, 0xc6, 0x01, 0x15, 0x47, 0x7e, 0x28,
	0x4e, 0x04, 0x11, 0xdc, 0xa1, 0xe7, 0x09, 0xe5, 0x02, 0xb7, 0xa1, 0x18, 0x13, 0x9f, 0x2a, 0x0e,
	0xb3, 0xbb, 0xd9, 0x99, 0x0e, 0x9a, 0x35, 0x72, 0x54, 0x46, 0xeb, 0x5b, 0x09, 0x36, 0xaf, 0x32,
	0xf0, 0x98, 0x45, 0x9c, 0xe2, 0xfb, 0x50, 0x8d, 0xe8, 0x07, 0xe1, 0x2e, 0xe4, 0xa9, 0xc8, 0xb4,
	0x63, 0xe2, 0x53, 0x7c, 0x00, 0x20, 0x13, 0x5c, 0x2e, 0x89, 0xea, 0x46, 0xb3, 0xd0, 0x36, 0xbb,
	0xed, 0xac, 0x66, 0x5e, 0x9b, 0xce, 0x2b, 0xe6, 0x51, 0x8d, 0x54, 0xa3, 0xc9, 0xa3, 0xfd, 0x1d,
	0x01, 0x38, 0x34, 0x4e, 0x84, 0x96, 0xa4, 0x01, 0xa6, 0x60, 0x82, 0x8c, 0xdc, 0x01, 0x4b, 0x22,
	0x2d, 0x4c, 0xc1, 0x01, 0x05, 0xed, 0x4b, 0x04, 0xdf, 0x85, 0x1a, 0x4f, 0x06, 0x03, 0xca, 0x79,
	0x9a, 0x62, 0xa8, 0x14, 0x2b, 0x05, 0x75, 0xd2, 0x0e, 0x6c, 0x8c, 0xa7, 0x9c, 0x2e, 0x19, 0xc5,
	0x67, 0xa4, 0x5e, 0x68, 0xa2, 0x36, 0x72, 0xae, 0x67, 0xf8, 0x53, 0x09, 0xe3, 0x6d, 0xc8, 0x41,
	0x6e, 0x9f, 0x0a, 0x52, 0x2f, 0xaa, 0xcc, 0xf5, 0x0c, 0xee, 0x51, 0x41, 0x66, 0x38, 0xf9, 0x80,
	0x8d, 0x69, 0xbd, 0x34, 0xcb, 0x79, 0x22, 0x61, 0xfb, 0x17, 0x82, 0x92, 0xda, 0x0e, 0xbf, 0x04,
	0x2b, 0x89, 0xa5, 0x09, 0xdc, 0xc1, 0x19, 0x1d, 0xbc, 0x4b, 0xc5, 0xdd, 0x59, 0x20, 0x54, 0xa6,
	0x87, 0x63, 0xea, 0xf2, 0x7d, 0x59, 0x8d, 0x5f, 0x80, 0x49, 0x12, 0x2f, 0x10, 0x29, 0x99, 0xb1,
	0x2a, 0x19, 0xa8, 0x6a, 0xcd, 0xf5, 0x1c, 0x2c, 0x2f, 0xe0, 0xe7, 0x09, 0x19, 0x05, 0xc3, 0x80,
	0x7a, 0x4a, 0x1e, 0xb3, 0x6b, 0x77, 0xb4, 0x83, 0x3b, 0x13, 0x07, 0x77, 0x4e, 0x27, 0x0e, 0xee,
	0x55, 0x2e, 0x2e, 0x1b, 0xe8, 0xe3, 0xcf, 0x06, 0x72, 0xae, 0x54, 0xda, 0x31, 0x54, 0xa7, 0x5f,
	0x16, 0x6f, 0xc3, 0x35, 0xe5, 0x8b, 0xc0, 0x53, 0xbb, 0x5a, 0xbd, 0xf5, 0x8b, 0xcb, 0xc6, 0xda,
	0x8f, 0xcb, 0x46, 0x59, 0xe6, 0x1c, 0x3e, 0x73, 0xca, 0xf2, 0xf5, 0xa1, 0x87, 0xf7, 0xa0, 0x34,
	0xf1, 0x8e, 0x6c, 0xbc, 0xb5, 0x60, 0x0b, 0x1d, 0xe9, 0x92, 0xd6, 0x67, 0x04, 0xf6, 0x34, 0x8b,
	0x8d, 0x89, 0x4f, 0x5f, 0x73, 0xe2, 0xd3, 0x95, 0x2f, 0x02, 0x3f, 0x86, 0xe2, 0x70, 0xcc, 0xc2,
	0x74, 0x86, 0x45, 0xcb, 0xaf, 0xa9, 0xe5, 0x55, 0x05, 0x7e, 0x08, 0x86, 0x60, 0x4b, 0x8a, 0xa6,
	0xeb, 0x0c, 0xc1, 0x5a, 0x5f, 0x0b, 0x70, 0x6b, 0xee, 0xe0, 0xff, 0x7f, 0x88, 0x1e, 0xe0, 0xf4,
	0x10, 0x15, 0x9f, 0x9b, 0x48, 0xc2, 0xf4, 0x20, 0x1f, 0xcd, 0x11, 0xf5, 0xcf, 0xae, 0xe9, 0x5d,
	0xe6, 0x5e, 0x6c, 0x44, 0x33, 0x88, 0xfd, 0x1e, 0xac, 0x7c, 0x8c, 0x5b, 0x50, 0x23, 0xc2, 0x1d,
	0x53, 0x2e, 0x5c, 0x75, 0x9b, 0x6a, 0x58, 0xe4, 0x98, 0x44, 0x38, 0x94, 0x8b, 0x53, 0x09, 0xe1,
	0x1e, 0x54, 0xa7, 0xbf, 0xbf, 0x95, 0x14, 0xce, 0xca, 0xec, 0x4f, 0x08, 0x36, 0x66, 0xc7, 0x5b,
	0xde, 0x63, 0x6f, 0xa0, 0x36, 0x4f, 0x96, 0xee, 0x72, 0xb2, 0x5c, 0x01, 0x2d, 0x9e, 0x8b, 0xba,
	0x5f, 0x10, 0x54, 0x64, 0x2f, 0x59, 0x8b, 0x8f, 0xc0, 0xca, 0x5b, 0x16, 0xdf, 0xfe, 0x9b, 0x95,
	0x95, 0x3b, 0xed, 0x3b, 0xff, 0x76, 0x3a, 0xee, 0xe7, 0x7e, 0xf3, 0xb9, 0xa5, 0xb7, 0x16, 0x0c,
	0xad, 0xc9, 0xef, 0x2d, 0xb5, 0x5a, 0xaf, 0xf8, 0xd6, 0x88, 0xfb, 0xfd, 0xb2, 0xfa, 0x0a, 0x0f,
	0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x9c, 0x09, 0xa0, 0xdc, 0x06, 0x00, 0x00,
}

type DRPCNodeMgmtClient interface {
	DRPCConn() drpc.Conn

	GetMgmtStats(ctx context.Context, in *GetMgmtStatsRequest) (*GetMgmtStatsResponse, error)
	GetMgmtStorageUsage(ctx context.Context, in *GetMgmtStorageUsageRequest) (*GetMgmtStorageUsageResponse, error)
}

type drpcNodeMgmtClient struct {
	cc drpc.Conn
}

func NewDRPCNodeMgmtClient(cc drpc.Conn) DRPCNodeMgmtClient {
	return &drpcNodeMgmtClient{cc}
}

func (c *drpcNodeMgmtClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcNodeMgmtClient) GetMgmtStats(ctx context.Context, in *GetMgmtStatsRequest) (*GetMgmtStatsResponse, error) {
	out := new(GetMgmtStatsResponse)
	err := c.cc.Invoke(ctx, "/nodemgmt.NodeMgmt/GetMgmtStats", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcNodeMgmtClient) GetMgmtStorageUsage(ctx context.Context, in *GetMgmtStorageUsageRequest) (*GetMgmtStorageUsageResponse, error) {
	out := new(GetMgmtStorageUsageResponse)
	err := c.cc.Invoke(ctx, "/nodemgmt.NodeMgmt/GetMgmtStorageUsage", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCNodeMgmtServer interface {
	GetMgmtStats(context.Context, *GetMgmtStatsRequest) (*GetMgmtStatsResponse, error)
	GetMgmtStorageUsage(context.Context, *GetMgmtStorageUsageRequest) (*GetMgmtStorageUsageResponse, error)
}

type DRPCNodeMgmtDescription struct{}

func (DRPCNodeMgmtDescription) NumMethods() int { return 2 }

func (DRPCNodeMgmtDescription) Method(n int) (string, drpc.Handler, interface{}, bool) {
	switch n {
	case 0:
		return "/nodemgmt.NodeMgmt/GetMgmtStats",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCNodeMgmtServer).
					GetMgmtStats(
						ctx,
						in1.(*GetMgmtStatsRequest),
					)
			}, DRPCNodeMgmtServer.GetMgmtStats, true
	case 1:
		return "/nodemgmt.NodeMgmt/GetMgmtStorageUsage",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCNodeMgmtServer).
					GetMgmtStorageUsage(
						ctx,
						in1.(*GetMgmtStorageUsageRequest),
					)
			}, DRPCNodeMgmtServer.GetMgmtStorageUsage, true
	default:
		return "", nil, nil, false
	}
}

func DRPCRegisterNodeMgmt(srv drpc.Server, impl DRPCNodeMgmtServer) {
	srv.Register(impl, DRPCNodeMgmtDescription{})
}

type DRPCNodeMgmt_GetMgmtStatsStream interface {
	drpc.Stream
	SendAndClose(*GetMgmtStatsResponse) error
}

type drpcNodeMgmtGetMgmtStatsStream struct {
	drpc.Stream
}

func (x *drpcNodeMgmtGetMgmtStatsStream) SendAndClose(m *GetMgmtStatsResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCNodeMgmt_GetMgmtStorageUsageStream interface {
	drpc.Stream
	SendAndClose(*GetMgmtStorageUsageResponse) error
}

type drpcNodeMgmtGetMgmtStorageUsageStream struct {
	drpc.Stream
}

func (x *drpcNodeMgmtGetMgmtStorageUsageStream) SendAndClose(m *GetMgmtStorageUsageResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeMgmtClient is the client API for NodeMgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeMgmtClient interface {
	GetMgmtStats(ctx context.Context, in *GetMgmtStatsRequest, opts ...grpc.CallOption) (*GetMgmtStatsResponse, error)
	GetMgmtStorageUsage(ctx context.Context, in *GetMgmtStorageUsageRequest, opts ...grpc.CallOption) (*GetMgmtStorageUsageResponse, error)
}

type nodeMgmtClient struct {
	cc *grpc.ClientConn
}

func NewNodeMgmtClient(cc *grpc.ClientConn) NodeMgmtClient {
	return &nodeMgmtClient{cc}
}

func (c *nodeMgmtClient) GetMgmtStats(ctx context.Context, in *GetMgmtStatsRequest, opts ...grpc.CallOption) (*GetMgmtStatsResponse, error) {
	out := new(GetMgmtStatsResponse)
	err := c.cc.Invoke(ctx, "/nodemgmt.NodeMgmt/GetMgmtStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeMgmtClient) GetMgmtStorageUsage(ctx context.Context, in *GetMgmtStorageUsageRequest, opts ...grpc.CallOption) (*GetMgmtStorageUsageResponse, error) {
	out := new(GetMgmtStorageUsageResponse)
	err := c.cc.Invoke(ctx, "/nodemgmt.NodeMgmt/GetMgmtStorageUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeMgmtServer is the server API for NodeMgmt service.
type NodeMgmtServer interface {
	GetMgmtStats(context.Context, *GetMgmtStatsRequest) (*GetMgmtStatsResponse, error)
	GetMgmtStorageUsage(context.Context, *GetMgmtStorageUsageRequest) (*GetMgmtStorageUsageResponse, error)
}

func RegisterNodeMgmtServer(s *grpc.Server, srv NodeMgmtServer) {
	s.RegisterService(&_NodeMgmt_serviceDesc, srv)
}

func _NodeMgmt_GetMgmtStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMgmtStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeMgmtServer).GetMgmtStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodemgmt.NodeMgmt/GetMgmtStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeMgmtServer).GetMgmtStats(ctx, req.(*GetMgmtStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeMgmt_GetMgmtStorageUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMgmtStorageUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeMgmtServer).GetMgmtStorageUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodemgmt.NodeMgmt/GetMgmtStorageUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeMgmtServer).GetMgmtStorageUsage(ctx, req.(*GetMgmtStorageUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeMgmt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodemgmt.NodeMgmt",
	HandlerType: (*NodeMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMgmtStats",
			Handler:    _NodeMgmt_GetMgmtStats_Handler,
		},
		{
			MethodName: "GetMgmtStorageUsage",
			Handler:    _NodeMgmt_GetMgmtStorageUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodemgmt.proto",
}
